language: node_js

node_js:
  - '6'

cache:
  directories:
    - node_modules

sudo: false

branches:
  except:
    - gh-pages

deploy:
  skip_cleanup: true
  provider: script
  script: sh ./.deploy.sh
  on:
    branch: master
